# Generated by Django 2.0 on 2017-12-12 13:33

import blog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171128_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.FileField(default='/default.png', storage=blog.storage.OverwriteStorage(), upload_to=''),
        ),
    ]
