# Generated by Django 2.0 on 2017-12-12 14:58

import blog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171212_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.FileField(default='/media/default.png', storage=blog.storage.OverwriteStorage(), upload_to=''),
        ),
    ]
