# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 15:16
from __future__ import unicode_literals

import blog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.TextField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=150)),
                ('tags', models.TextField()),
                ('gitLink', models.URLField()),
                ('image', models.FileField(default='/media/default.png', storage=blog.storage.OverwriteStorage(), upload_to='')),
            ],
        ),
    ]
