# Generated by Django 2.0 on 2017-12-12 15:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 12, 12, 15, 5, 54, 904053, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
